# Generated by Django 6.0.6 on 2026-07-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_car_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('aadhaar', models.CharField(max_length=20)),
            ],
        ),
    ]
