# Generated by Django 6.0.6 on 2026-07-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0006_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
